import { Product } from './types';

export const RINGS_DATA: Product[] = [
  // --- ANELLI (1001 - 1014) ---
  {
    id: 1001,
    title: "Classic Round Solitaire",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=2070",
    metal: "18k White Gold",
    estimated_weight: 3.5,
    head_style: 'Solitaire',
    shank_style: 'Decorated Band',
    primary_stone_shape: "Round",
    primary_stone_count: 1,
    primary_stone_length: 6.5,
    is_active: true
  },
  {
    id: 1002,
    title: "Oval Halo Pavé",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1589674781757-3a045c644949?q=80&w=2070",
    metal: "18k Yellow Gold",
    estimated_weight: 4.2,
    head_style: 'Halo',
    shank_style: 'Pavé',
    primary_stone_shape: "Oval",
    primary_stone_count: 1,
    primary_stone_length: 8.0,
    primary_stone_width: 6.0,
    is_active: true
  },
  {
    id: 1003,
    title: "Emerald Cut Trilogy",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1598560917505-59a3ad559071?q=80&w=2070",
    metal: "Platinum",
    estimated_weight: 5.8,
    head_style: 'Trilogy',
    shank_style: 'Signet',
    primary_stone_shape: "Emerald",
    primary_stone_count: 1,
    primary_stone_length: 7.0,
    primary_stone_width: 5.0,
    secondary_stone_shape: "Baguette",
    secondary_stone_count: 2,
    is_active: true
  },
  {
    id: 1004,
    title: "Modern Wedding Band",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1603561596112-0a132b757442?q=80&w=2070",
    metal: "18k Rose Gold",
    estimated_weight: 6.5,
    shank_style: 'Wedding Band',
    is_active: true
  },
  {
    id: 1005,
    title: "Pear Diamond Pavé",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1590548784585-643d2b9f2925?q=80&w=2000",
    metal: "18k White Gold",
    estimated_weight: 4.8,
    head_style: 'Solitaire',
    shank_style: 'Pavé',
    primary_stone_shape: "Pear",
    primary_stone_count: 1,
    primary_stone_length: 9.0,
    primary_stone_width: 6.0,
    secondary_stone_shape: "Round",
    secondary_stone_count: 18,
    is_active: true
  },
  {
    id: 1006,
    title: "Vintage Cluster Crown",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1630006176266-6466e74463f7?q=80&w=2000",
    metal: "18k Yellow Gold",
    estimated_weight: 5.2,
    head_style: 'Cluster',
    shank_style: 'Decorated Band',
    primary_stone_shape: "Round",
    primary_stone_count: 7,
    primary_stone_length: 3.0,
    is_active: true
  },
  {
    id: 1007,
    title: "Royal Cushion Halo",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1543508282-5c1f427f023f?q=80&w=2000",
    metal: "Platinum",
    estimated_weight: 6.1,
    head_style: 'Halo',
    shank_style: 'Eternity',
    primary_stone_shape: "Cushion",
    primary_stone_count: 1,
    primary_stone_length: 7.5,
    primary_stone_width: 7.5,
    secondary_stone_shape: "Round",
    secondary_stone_count: 32,
    is_active: true
  },
  {
    id: 1008,
    title: "Two Stones Bypass",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1627221564420-9017ef0fc763?q=80&w=2000",
    metal: "18k Rose Gold",
    estimated_weight: 3.9,
    head_style: 'Two Stones',
    shank_style: 'Decorated Band',
    primary_stone_shape: "Pear",
    primary_stone_count: 2,
    primary_stone_length: 5.0,
    primary_stone_width: 3.5,
    is_active: true
  },
  {
    id: 1009,
    title: "Bold Men's Signet",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?q=80&w=2000",
    metal: "18k Yellow Gold",
    estimated_weight: 12.5,
    shank_style: 'Signet',
    primary_stone_shape: "Square",
    primary_stone_count: 1,
    primary_stone_length: 10.0,
    primary_stone_width: 10.0,
    is_active: true
  },
  {
    id: 1010,
    title: "Minimalist Marquise",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?q=80&w=2000",
    metal: "18k White Gold",
    estimated_weight: 2.8,
    head_style: 'Solitaire',
    shank_style: 'Decorated Band',
    primary_stone_shape: "Marquise",
    primary_stone_count: 1,
    primary_stone_length: 10.0,
    primary_stone_width: 5.0,
    is_active: true
  },
  {
    id: 1011,
    title: "Princess Cut Trilogy",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1599459182882-628d8b672722?q=80&w=2000",
    metal: "18k White Gold",
    estimated_weight: 4.5,
    head_style: 'Trilogy',
    shank_style: 'Pavé',
    primary_stone_shape: "Princess",
    primary_stone_count: 3,
    primary_stone_length: 4.5,
    primary_stone_width: 4.5,
    is_active: true
  },
  {
    id: 1012,
    title: "Full Eternity Diamond",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1635767798638-3e25273a8236?q=80&w=2000",
    metal: "Platinum",
    estimated_weight: 5.5,
    shank_style: 'Eternity',
    primary_stone_shape: "Round",
    primary_stone_count: 22,
    primary_stone_length: 3.0,
    is_active: true
  },
  {
    id: 1013,
    title: "Heart Solitaire Promise",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?q=80&w=2000",
    metal: "18k Rose Gold",
    estimated_weight: 3.2,
    head_style: 'Solitaire',
    shank_style: 'Decorated Band',
    primary_stone_shape: "Heart",
    primary_stone_count: 1,
    primary_stone_length: 6.0,
    primary_stone_width: 6.0,
    is_active: true
  },
  {
    id: 1014,
    title: "Double Halo Emerald",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?q=80&w=2000",
    metal: "18k White Gold",
    estimated_weight: 7.2,
    head_style: 'Halo',
    shank_style: 'Pavé',
    primary_stone_shape: "Emerald",
    primary_stone_count: 1,
    primary_stone_length: 8.0,
    primary_stone_width: 6.0,
    secondary_stone_shape: "Round",
    secondary_stone_count: 56,
    is_active: true
  },

  // --- EARRINGS (201 - 210) ---
  {
    id: 201,
    title: "Classic Diamond Studs",
    category: 'earrings',
    price: "450",
    img: "https://images.unsplash.com/photo-1590548784585-645d8903e86a?q=80&w=800",
    metal: "18k White Gold",
    estimated_weight: 1.8,
    is_active: true,
    earring_style: 'Studs',
    closure: 'Pin',
    primary_stone_shape: "Round",
    primary_stone_count: 2,
    primary_stone_length: 4.5
  },
  {
    id: 202,
    title: "Celestial Huggies",
    category: 'earrings',
    price: "890",
    img: "https://images.unsplash.com/photo-1630019058353-5244f78d0674?q=80&w=800",
    metal: "18k Yellow Gold",
    estimated_weight: 3.2,
    is_active: true,
    earring_style: 'Huggies',
    closure: 'Hinge',
    primary_stone_shape: "Round",
    primary_stone_count: 12,
    primary_stone_length: 1.5,
    secondary_stone_shape: "None"
  },
  {
    id: 203,
    title: "Royal Emerald Drop",
    category: 'earrings',
    price: "2400",
    img: "https://images.unsplash.com/photo-1635767798638-3e25273a8236?q=80&w=800",
    metal: "Platinum",
    estimated_weight: 6.5,
    is_active: true,
    earring_style: 'Drop',
    closure: 'Leverback',
    primary_stone_shape: "Emerald",
    primary_stone_count: 2,
    primary_stone_length: 8.0,
    primary_stone_width: 6.0,
    secondary_stone_shape: "Round",
    secondary_stone_count: 24,
    secondary_stone_length: 1.2
  },
  {
    id: 204,
    title: "Infinite Pave Hoops",
    category: 'earrings',
    price: "1250",
    img: "https://images.unsplash.com/photo-1616113702130-1b20b2401974?q=80&w=800",
    metal: "18k Rose Gold",
    estimated_weight: 4.8,
    is_active: true,
    earring_style: 'Hoops',
    closure: 'Hinge',
    primary_stone_shape: "Round",
    primary_stone_count: 40,
    primary_stone_length: 1.3
  },
  {
    id: 205,
    title: "Starlight Ear Climbers",
    category: 'earrings',
    price: "670",
    img: "https://images.unsplash.com/photo-1535633302703-b0703af6c3af?q=80&w=800",
    metal: "18k White Gold",
    estimated_weight: 2.1,
    is_active: true,
    earring_style: 'Ear Climbers / Crawlers',
    closure: 'Pin',
    primary_stone_shape: "Marquise",
    primary_stone_count: 6,
    primary_stone_length: 4.0,
    primary_stone_width: 2.0
  },
  {
    id: 206,
    title: "Vintage Halo Solitaire",
    category: 'earrings',
    price: "1100",
    img: "https://images.unsplash.com/photo-1603912627214-935f5f4b0229?q=80&w=800",
    metal: "18k Yellow Gold",
    estimated_weight: 2.8,
    is_active: true,
    earring_style: 'Halo',
    closure: 'Omega',
    primary_stone_shape: "Cushion",
    primary_stone_count: 2,
    primary_stone_length: 5.5,
    primary_stone_width: 5.5,
    secondary_stone_shape: "Round",
    secondary_stone_count: 32,
    secondary_stone_length: 1.0
  },
  {
    id: 207,
    title: "Modern Pearl Ear Jackets",
    category: 'earrings',
    price: "550",
    img: "https://images.unsplash.com/photo-1596944214946-174074c6f99e?q=80&w=800",
    metal: "18k Rose Gold",
    estimated_weight: 3.5,
    is_active: true,
    earring_style: 'Ear Jackets',
    closure: 'Pin',
    primary_stone_shape: "Round",
    primary_stone_count: 2,
    primary_stone_length: 6.0
  },
  {
    id: 208,
    title: "Gothic Chandelier",
    category: 'earrings',
    price: "3200",
    img: "https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?q=80&w=800",
    metal: "Platinum",
    estimated_weight: 12.4,
    is_active: true,
    earring_style: 'Chandelier',
    closure: 'Fishhook',
    primary_stone_shape: "Pear",
    primary_stone_count: 4,
    primary_stone_length: 7.0,
    primary_stone_width: 5.0,
    secondary_stone_shape: "Baguette",
    secondary_stone_count: 12,
    secondary_stone_length: 3.0,
    secondary_stone_width: 1.5
  },
  {
    id: 209,
    title: "Minimalist Ear Cuffs",
    category: 'earrings',
    price: "290",
    img: "https://images.unsplash.com/photo-1617114919297-3c8ddb01f599?q=80&w=800",
    metal: "18k Yellow Gold",
    estimated_weight: 1.5,
    is_active: true,
    earring_style: 'Ear Cuffs',
    closure: 'Pin',
    primary_stone_shape: "None",
    primary_stone_count: 0
  },
  {
    id: 210,
    title: "Double Halo Princess",
    category: 'earrings',
    price: "1850",
    img: "https://images.unsplash.com/photo-1588444839138-eb6a5c305a4a?q=80&w=800",
    metal: "18k White Gold",
    estimated_weight: 5.2,
    is_active: true,
    earring_style: 'Halo',
    closure: 'Pin',
    primary_stone_shape: "Princess",
    primary_stone_count: 2,
    primary_stone_length: 4.0,
    primary_stone_width: 4.0,
    secondary_stone_shape: "Round",
    secondary_stone_count: 48,
    secondary_stone_length: 0.8
  },
  // --- NUOVI ARRIVI EARRINGS (211 - 220) ---
  {
    id: 211,
    title: "Large Skinny Hoops",
    category: 'earrings',
    price: "600",
    img: "https://images.unsplash.com/photo-1629224316810-9d8805b95e76?q=80&w=800",
    metal: "18k Yellow Gold",
    estimated_weight: 3.2,
    earring_style: 'Hoops',
    closure: 'Hinge',
    earring_diameter: 60, // Molto grandi ma leggeri
    is_active: true
  },
  {
    id: 212,
    title: "Diamond Star Huggies",
    category: 'earrings',
    price: "890",
    img: "https://images.unsplash.com/photo-1630030538465-35ac30bc35ee?q=80&w=800",
    metal: "18k White Gold",
    estimated_weight: 2.8,
    earring_style: 'Huggies',
    closure: 'Hinge',
    earring_diameter: 14,
    primary_stone_shape: "Round",
    primary_stone_count: 12,
    is_active: true
  },
  {
    id: 213,
    title: "Art Deco Emerald Drops",
    category: 'earrings',
    price: "4200",
    img: "https://images.unsplash.com/photo-1617114919297-3c8ddb01f599?q=80&w=800",
    metal: "Platinum",
    estimated_weight: 7.5,
    earring_style: 'Drop',
    closure: 'Leverback',
    primary_stone_shape: "Emerald",
    primary_stone_count: 2,
    primary_stone_length: 6.0,
    primary_stone_width: 4.0,
    secondary_stone_shape: "Baguette",
    secondary_stone_count: 8,
    is_active: true
  },
  {
    id: 214,
    title: "Gold Bamboo Hoops",
    category: 'earrings',
    price: "1150",
    img: "https://images.unsplash.com/photo-1633819260205-d2c94584485c?q=80&w=800",
    metal: "18k Yellow Gold",
    estimated_weight: 9.1,
    earring_style: 'Hoops',
    closure: 'Hinge',
    earring_diameter: 40,
    is_active: true
  },
  {
    id: 215,
    title: "Floral Diamond Climbers",
    category: 'earrings',
    price: "1450",
    img: "https://images.unsplash.com/photo-1596944211754-063a83f98285?q=80&w=800",
    metal: "18k Rose Gold",
    estimated_weight: 3.4,
    earring_style: 'Ear Climbers / Crawlers',
    closure: 'Pin',
    primary_stone_shape: "Marquise",
    primary_stone_count: 10,
    is_active: true
  },
  {
    id: 216,
    title: "Twisted Rope Huggies",
    category: 'earrings',
    price: "350",
    img: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=800",
    metal: "18k Yellow Gold",
    estimated_weight: 2.1,
    earring_style: 'Huggies',
    closure: 'Hinge',
    earring_diameter: 15,
    is_active: true
  },
  {
    id: 217,
    title: "Ruby Halo Studs",
    category: 'earrings',
    price: "2100",
    img: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=800",
    metal: "18k White Gold",
    estimated_weight: 2.9,
    earring_style: 'Halo',
    closure: 'Pin',
    primary_stone_shape: "Round",
    primary_stone_count: 2,
    primary_stone_length: 4.5,
    secondary_stone_shape: "Round",
    secondary_stone_count: 24,
    is_active: true
  },
  {
    id: 218,
    title: "Double Chain Ear Cuffs",
    category: 'earrings',
    price: "550",
    img: "https://images.unsplash.com/photo-1588444837495-c6cfaf504670?q=80&w=800",
    metal: "18k Yellow Gold",
    estimated_weight: 2.3,
    earring_style: 'Ear Cuffs',
    is_active: true
  },
  {
    id: 219,
    title: "Regal Chandelier Drops",
    category: 'earrings',
    price: "5800",
    img: "https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?q=80&w=800",
    metal: "18k White Gold",
    estimated_weight: 18.5,
    earring_style: 'Chandelier',
    closure: 'Fishhook',
    primary_stone_shape: "Pear",
    primary_stone_count: 6,
    secondary_stone_shape: "Round",
    secondary_stone_count: 120,
    is_active: true
  },
  {
    id: 220,
    title: "Modern Square Hoops",
    category: 'earrings',
    price: "920",
    img: "https://images.unsplash.com/photo-1617114919297-3c8ddb01f599?q=80&w=800",
    metal: "18k Yellow Gold",
    estimated_weight: 5.8,
    earring_style: 'Hoops',
    closure: 'Hinge',
    earring_diameter: 30,
    is_active: true
  },
  // --- PENDANTS (301 - 310) ---
  {
    id: 301,
    title: "Classic Solitaire Pendant",
    category: 'pendants',
    price: "850",
    img: "https://images.unsplash.com/photo-1599643478123-242f19bab944?q=80&w=800",
    metal: "18k White Gold",
    estimated_weight: 1.2,
    primary_stone_shape: "Round",
    primary_stone_count: 1,
    primary_stone_length: 6.5,
    is_active: true
  },
  {
    id: 302,
    title: "Vintage Emerald Cut Medallion",
    category: 'pendants',
    price: "2400",
    img: "https://images.unsplash.com/photo-1611085583191-a3b130a8b17e?q=80&w=800",
    metal: "18k Yellow Gold",
    estimated_weight: 5.5,
    primary_stone_shape: "Emerald",
    primary_stone_count: 1,
    primary_stone_length: 8.0,
    primary_stone_width: 6.0,
    is_active: true
  },
  {
    id: 303,
    title: "Heart of Oceans Sapphire",
    category: 'pendants',
    price: "3200",
    img: "https://images.unsplash.com/photo-1602751584446-8f82a6908595?q=80&w=800",
    metal: "Platinum",
    estimated_weight: 4.8,
    primary_stone_shape: "Heart",
    primary_stone_count: 1,
    secondary_stone_shape: "Round",
    secondary_stone_count: 20,
    is_active: true
  },
  {
    id: 304,
    title: "Minimalist Bar Pendant",
    category: 'pendants',
    price: "450",
    img: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=800",
    metal: "18k Rose Gold",
    estimated_weight: 2.5,
    is_active: true
  },
  {
    id: 305,
    title: "Pear Drop Halo Pendant",
    category: 'pendants',
    price: "1850",
    img: "https://images.unsplash.com/photo-1635767798638-3e25273a8236?q=80&w=800",
    metal: "18k White Gold",
    estimated_weight: 3.1,
    primary_stone_shape: "Pear",
    primary_stone_count: 1,
    secondary_stone_shape: "Round",
    secondary_stone_count: 15,
    is_active: true
  },
  {
    id: 306,
    title: "Celestial Moon Diamond",
    category: 'pendants',
    price: "980",
    img: "https://images.unsplash.com/photo-1630030538465-35ac30bc35ee?q=80&w=800",
    metal: "18k Yellow Gold",
    estimated_weight: 2.2,
    secondary_stone_shape: "Round",
    secondary_stone_count: 8,
    is_active: true
  },
  {
    id: 307,
    title: "Modern Asscher Geometric",
    category: 'pendants',
    price: "2900",
    img: "https://images.unsplash.com/photo-1617114919297-3c8ddb01f599?q=80&w=800",
    metal: "Platinum",
    estimated_weight: 6.2,
    primary_stone_shape: "Asscher",
    primary_stone_count: 1,
    primary_stone_length: 7.0,
    is_active: true
  },
  {
    id: 308,
    title: "Three-Stone Journey Pendant",
    category: 'pendants',
    price: "1550",
    img: "https://images.unsplash.com/photo-1596944211754-063a83f98285?q=80&w=800",
    metal: "18k White Gold",
    estimated_weight: 2.8,
    primary_stone_shape: "Round",
    primary_stone_count: 3,
    is_active: true
  },
  {
    id: 309,
    title: "Bohemian Marquise Leaf",
    category: 'pendants',
    price: "750",
    img: "https://images.unsplash.com/photo-1633819260205-d2c94584485c?q=80&w=800",
    metal: "18k Rose Gold",
    estimated_weight: 3.5,
    primary_stone_shape: "Marquise",
    primary_stone_count: 5,
    is_active: true
  },
  {
    id: 310,
    title: "Grand Cushion Statement",
    category: 'pendants',
    price: "5500",
    img: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=800",
    metal: "18k Yellow Gold",
    estimated_weight: 8.9,
    primary_stone_shape: "Cushion",
    primary_stone_count: 1,
    primary_stone_length: 10.0,
    secondary_stone_shape: "Round",
    secondary_stone_count: 40,
    is_active: true
  },
  // --- BRACELETS (401 - 410) ---
  {
    id: 401,
    title: "Classic Diamond Tennis Bracelet",
    category: 'bracelets',
    price: "4500",
    img: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=800",
    metal: "18k White Gold",
    estimated_weight: 12.5,
    bracelet_style: 'Tennis',
    bracelet_length: 18,
    primary_stone_shape: "Round",
    primary_stone_count: 55,
    is_active: true
  },
  {
    id: 402,
    title: "Modern High-Polish Bangle",
    category: 'bracelets',
    price: "1800",
    img: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=800",
    metal: "18k Yellow Gold",
    estimated_weight: 18.2,
    bracelet_style: 'Bangle',
    is_active: true
  },
  {
    id: 403,
    title: "Emerald Cut Eternity Link",
    category: 'bracelets',
    price: "6200",
    img: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=800",
    metal: "Platinum",
    estimated_weight: 15.8,
    bracelet_style: 'Link',
    primary_stone_shape: "Emerald",
    primary_stone_count: 42,
    is_active: true
  },
  {
    id: 404,
    title: "Rose Gold Pavé Cuff",
    category: 'bracelets',
    price: "2900",
    img: "https://images.unsplash.com/photo-1633819260205-d2c94584485c?q=80&w=800",
    metal: "18k Rose Gold",
    estimated_weight: 22.0,
    bracelet_style: 'Cuff',
    secondary_stone_shape: "Round",
    secondary_stone_count: 120,
    is_active: true
  },
  {
    id: 405,
    title: "Sapphire Accent Chain",
    category: 'bracelets',
    price: "1150",
    img: "https://images.unsplash.com/photo-1596944211754-063a83f98285?q=80&w=800",
    metal: "18k Yellow Gold",
    estimated_weight: 6.4,
    bracelet_style: 'Chain',
    primary_stone_shape: "Oval",
    primary_stone_count: 3,
    is_active: true
  },
  {
    id: 406,
    title: "Heavy Curb Link Bracelet",
    category: 'bracelets',
    price: "2100",
    img: "https://images.unsplash.com/photo-1617114919297-3c8ddb01f599?q=80&w=800",
    metal: "18k White Gold",
    estimated_weight: 25.5,
    bracelet_style: 'Link',
    is_active: true
  },
  {
    id: 407,
    title: "Princess Cut Tennis Line",
    category: 'bracelets',
    price: "5800",
    img: "https://images.unsplash.com/photo-1602751584446-8f82a6908595?q=80&w=800",
    metal: "18k White Gold",
    estimated_weight: 14.0,
    bracelet_style: 'Tennis',
    primary_stone_shape: "Princess",
    primary_stone_count: 48,
    is_active: true
  },
  {
    id: 408,
    title: "Minimalist Bead Bracelet",
    category: 'bracelets',
    price: "550",
    img: "https://images.unsplash.com/photo-1588444837495-c6cfaf504670?q=80&w=800",
    metal: "18k Yellow Gold",
    estimated_weight: 4.2,
    bracelet_style: 'Chain',
    is_active: true
  },
  {
    id: 409,
    title: "Diamond Halo Bangle",
    category: 'bracelets',
    price: "3400",
    img: "https://images.unsplash.com/photo-1630030538465-35ac30bc35ee?q=80&w=800",
    metal: "18k White Gold",
    estimated_weight: 16.5,
    bracelet_style: 'Bangle',
    primary_stone_shape: "Round",
    primary_stone_count: 1,
    secondary_stone_shape: "Round",
    secondary_stone_count: 20,
    is_active: true
  },
  {
    id: 410,
    title: "Twisted Rope Cuff",
    category: 'bracelets',
    price: "1350",
    img: "https://images.unsplash.com/photo-1635767798638-3e25273a8236?q=80&w=800",
    metal: "18k Rose Gold",
    estimated_weight: 19.8,
    bracelet_style: 'Cuff',
    is_active: true
  },
  {
    id: 411,
    title: "Empress Diamond Tennis",
    category: 'bracelets',
    price: "5200",
    img: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=800",
    metal: "18k White Gold",
    estimated_weight: 14.5,
    bracelet_style: 'Tennis',
    closure: 'Box Clasp', // Chiusura sicura per tennis
    bracelet_length: 17,
    is_active: true
  },
  {
    id: 412,
    title: "Sculptural Gold Bangle",
    category: 'bracelets',
    price: "2100",
    img: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=800",
    metal: "18k Yellow Gold",
    estimated_weight: 22.8,
    bracelet_style: 'Bangle',
    inner_diameter: 62, // Dato per il filtro Bangle
    is_active: true
  }
];