import { Product } from './types';

export const RINGS_DATA: Product[] = [
  // ... i 4 che avevi già (1001-1004) ...
  {
    id: 1001,
    title: "Classic Round Solitaire",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=2070",
    metal: "18k White Gold",
    estimated_weight: 3.5,
    head_style: 'Solitaire',
    shank_style: 'Decorated Band',
    primary_stone_shape: "Round",
    primary_stone_count: 1,
    primary_stone_length: 6.5,
    is_active: true
  },
  {
    id: 1002,
    title: "Oval Halo Pavé",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1589674781757-3a045c644949?q=80&w=2070",
    metal: "18k Yellow Gold",
    estimated_weight: 4.2,
    head_style: 'Halo',
    shank_style: 'Pavé',
    primary_stone_shape: "Oval",
    primary_stone_count: 1,
    primary_stone_length: 8.0,
    primary_stone_width: 6.0,
    is_active: true
  },
  {
    id: 1003,
    title: "Emerald Cut Trilogy",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1598560917505-59a3ad559071?q=80&w=2070",
    metal: "Platinum",
    estimated_weight: 5.8,
    head_style: 'Trilogy',
    shank_style: 'Signet',
    primary_stone_shape: "Emerald",
    primary_stone_count: 1,
    primary_stone_length: 7.0,
    primary_stone_width: 5.0,
    secondary_stone_shape: "Baguette",
    secondary_stone_count: 2,
    is_active: true
  },
  {
    id: 1004,
    title: "Modern Wedding Band",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1603561596112-0a132b757442?q=80&w=2070",
    metal: "18k Rose Gold",
    estimated_weight: 6.5,
    shank_style: 'Wedding Band',
    is_active: true
  },

  // --- NUOVI 10 ANELLI ---
  {
    id: 1005,
    title: "Pear Diamond Pavé",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1590548784585-643d2b9f2925?q=80&w=2000",
    metal: "18k White Gold",
    estimated_weight: 4.8,
    head_style: 'Solitaire',
    shank_style: 'Pavé',
    primary_stone_shape: "Pear",
    primary_stone_count: 1,
    primary_stone_length: 9.0,
    primary_stone_width: 6.0,
    secondary_stone_shape: "Round",
    secondary_stone_count: 18,
    is_active: true
  },
  {
    id: 1006,
    title: "Vintage Cluster Crown",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1630006176266-6466e74463f7?q=80&w=2000",
    metal: "18k Yellow Gold",
    estimated_weight: 5.2,
    head_style: 'Cluster',
    shank_style: 'Decorated Band',
    primary_stone_shape: "Round",
    primary_stone_count: 7,
    primary_stone_length: 3.0,
    is_active: true
  },
  {
    id: 1007,
    title: "Royal Cushion Halo",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1543508282-5c1f427f023f?q=80&w=2000",
    metal: "Platinum",
    estimated_weight: 6.1,
    head_style: 'Halo',
    shank_style: 'Eternity',
    primary_stone_shape: "Cushion",
    primary_stone_count: 1,
    primary_stone_length: 7.5,
    primary_stone_width: 7.5,
    secondary_stone_shape: "Round",
    secondary_stone_count: 32,
    is_active: true
  },
  {
    id: 1008,
    title: "Two Stones Bypass",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1627221564420-9017ef0fc763?q=80&w=2000",
    metal: "18k Rose Gold",
    estimated_weight: 3.9,
    head_style: 'Two Stones',
    shank_style: 'Decorated Band',
    primary_stone_shape: "Pear",
    primary_stone_count: 2,
    primary_stone_length: 5.0,
    primary_stone_width: 3.5,
    is_active: true
  },
  {
    id: 1009,
    title: "Bold Men's Signet",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?q=80&w=2000",
    metal: "18k Yellow Gold",
    estimated_weight: 12.5,
    shank_style: 'Signet',
    primary_stone_shape: "Square",
    primary_stone_count: 1,
    primary_stone_length: 10.0,
    primary_stone_width: 10.0,
    is_active: true
  },
  {
    id: 1010,
    title: "Minimalist Marquise",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?q=80&w=2000",
    metal: "18k White Gold",
    estimated_weight: 2.8,
    head_style: 'Solitaire',
    shank_style: 'Decorated Band',
    primary_stone_shape: "Marquise",
    primary_stone_count: 1,
    primary_stone_length: 10.0,
    primary_stone_width: 5.0,
    is_active: true
  },
  {
    id: 1011,
    title: "Princess Cut Trilogy",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1599459182882-628d8b672722?q=80&w=2000",
    metal: "18k White Gold",
    estimated_weight: 4.5,
    head_style: 'Trilogy',
    shank_style: 'Pavé',
    primary_stone_shape: "Princess",
    primary_stone_count: 3,
    primary_stone_length: 4.5,
    primary_stone_width: 4.5,
    is_active: true
  },
  {
    id: 1012,
    title: "Full Eternity Diamond",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1635767798638-3e25273a8236?q=80&w=2000",
    metal: "Platinum",
    estimated_weight: 5.5,
    shank_style: 'Eternity',
    primary_stone_shape: "Round",
    primary_stone_count: 22,
    primary_stone_length: 3.0,
    is_active: true
  },
  {
    id: 1013,
    title: "Heart Solitaire Promise",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?q=80&w=2000",
    metal: "18k Rose Gold",
    estimated_weight: 3.2,
    head_style: 'Solitaire',
    shank_style: 'Decorated Band',
    primary_stone_shape: "Heart",
    primary_stone_count: 1,
    primary_stone_length: 6.0,
    primary_stone_width: 6.0,
    is_active: true
  },
  {
    id: 1014,
    title: "Double Halo Emerald",
    category: 'rings',
    price: "Contact for Quote",
    img: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?q=80&w=2000",
    metal: "18k White Gold",
    estimated_weight: 7.2,
    head_style: 'Halo',
    shank_style: 'Pavé',
    primary_stone_shape: "Emerald",
    primary_stone_count: 1,
    primary_stone_length: 8.0,
    primary_stone_width: 6.0,
    secondary_stone_shape: "Round",
    secondary_stone_count: 56,
    is_active: true
  }
];